CREATE TABLE articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url TEXT NOT NULL,
    headline TEXT NOT NULL,
    summary TEXT NOT NULL,
    text TEXT NOT NULL,
    image TEXT NOT NULL,
    categories ARRAY NOT NULL,
    comments ARRAY,
    favorite BOOLEAN
);